SELECT e.ID
FROM ECOLI_DATA e
WHERE e.PARENT_ID IN(
    SELECT s.ID
    FROM ECOLI_DATA s
    WHERE s.PARENT_ID IN(
        SELECT f.ID
        FROM ECOLI_DATA f
        WHERE f.PARENT_ID IS NULL
    )
)